application: mysitepoll
version: 1
runtime: python27
api_version: 1
threadsafe:true

handlers:
- url: /
  script: home.app

- url: /index\.html
  script: home.app

- url: /admin/.*
  script:admin.app
  login: admin
