application: mysitepoll
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.application

- url: /index\.html
  script: home.application

- url: /admin/.*
  script: admin.application
  login: admin
